---
maven_versions:
  "3.8.8":
    url: "https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz"
    path: "/opt/maven3.8"

  "3.9.11":
    url: "https://archive.apache.org/dist/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz"
    path: "/opt/maven3.9"
