---
- block:

    - name: Install Maven
      include_tasks: "../../common/tasks/installer_by_download.yml"
      vars:
        tool_name: "maven"
        tool_url: "{{ maven_versions[maven_version].url }}"
        tool_checksum_url: "{{ maven_versions[maven_version].checksum_url }}"
        tool_checksum_algorithm: "{{ maven_versions[maven_version].checksum_algorithm }}"
        tool_path: "{{ maven_versions[maven_version].path }}"
        tool_profile_content: |
          export MAVEN_HOME="{{ maven_versions[maven_version].path }}"
          export PATH=$MAVEN_HOME/bin:$PATH
        tool_bin_name: "mvn"
        tool_version_arg: "-version"
        tool_version: "{{ maven_version }}"

    - name: Set Maven status success
      set_fact:
        maven_status: "success"

  rescue:

    - name: Set Maven status failed
      set_fact:
        maven_status: "failed"

  always:

    - name: Add Maven to install summary
      set_fact:
        install_summary: >-
          {{ install_summary + [ {
            'tool': 'maven',
            'version': maven_version,
            'path': maven_versions[maven_version].path,
            'status': maven_status | default('failed')
          } ] }}