---
- block:

    - name: Install JDK
      include_tasks: "../../common/tasks/installer_by_download.yml"
      vars:
        tool_name: "jdk"
        tool_url: "{{ jdk_versions[jdk_version].url }}"
        tool_checksum_url: "{{ jdk_versions[jdk_version].checksum_url }}"
        tool_checksum_algorithm: "{{ jdk_versions[jdk_version].checksum_algorithm }}"
        tool_path: "{{ jdk_versions[jdk_version].path }}"
        tool_profile_content: |
          export JAVA_HOME="{{ jdk_versions[jdk_version].path }}"
          export PATH=$JAVA_HOME/bin:$PATH
        tool_bin_name: "java"
        tool_version_arg: "-version"
        tool_version: "{{ jdk_version }}"

    - name: Set JDK status success
      set_fact:
        jdk_status: "success"

  rescue:
    - name: Set JDK status failed
      set_fact:
        jdk_status: "failed"

  always:
    - name: Add JDK to install summary
      set_fact:
        install_summary: >-
          {{ install_summary + [ {
            'tool': 'jdk',
            'version': jdk_version,
            'path': jdk_versions[jdk_version].path,
            'status': jdk_status | default('failed')
          } ] }}