---
gradle_versions:
  "9.4.0":
    url: "https://services.gradle.org/distributions/gradle-9.4.0-bin.zip"
    checksum_url: "https://services.gradle.org/distributions/gradle-9.4.0-bin.zip.sha256"
    checksum_algorithm: "sha256"
    path: "{{ install_dir }}/gradle"

  "8.14.5":
    url: "https://services.gradle.org/distributions/gradle-8.14.5-bin.zip"
    checksum_url: "https://services.gradle.org/distributions/gradle-8.14.5-bin.zip.sha256"
    checksum_algorithm: "sha256"
    path: "{{ install_dir }}/gradle"
